### ISSUE TITLE
'createLocation' is not exported from 'history'.

### ISSUE THREAD

**Issue by DavidMarioLC** [remix-run/history#809]
Failed to compile.

./node_modules/react-router/esm/react-router.js
Attempted import error: 'createLocation' is not exported from 'history'.

**Comment by sadewa25** [comment]
Downgrade your history library to 4.10.1 in package.json.

**Comment by ycjcl868** [comment]
+1

**Comment by publicJorn** [comment]
v5.0.0 was [released](https://github.com/ReactTraining/history/releases/tag/v5.0.0) on 12 Jun 2020

This is a breaking change, yet it is not listed anywhere.

What was the reason for removing it? Is there a known alternative?  
Is there anything the community can do to sort this out properly?

**Comment by tomas-vodrazka** [comment]
Hello, any update on this issue? Thanks 🙏 @DavidMarioLC @publicJorn

**Comment by mjackson** [comment]
This is a breaking change from v4. This API is not available in v5. Please see #811
