### ISSUE TITLE
Upgrading from 4.10.1 to 5.0.0: history/index"' has no exported member 'LocationState'.  TS2694

### ISSUE THREAD

**Issue by tomaszs** [remix-run/history#835]
Upgrading from 4.10.1 to 5.0.0 causes:

```
Namespace '"C:/myurl/node_modules/history/index"' has no exported member 'LocationState'.  TS2694

    53 | export class HashRouter extends React.Component<HashRouterProps, any> {}
    54 |
  > 55 | export interface LinkProps<S = H.LocationState> extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
       |                                  ^
    56 |     component?: React.ComponentType<any>;
    57 |     to: H.LocationDescriptor<S> | ((location: H.Location<S>) => H.LocationDescriptor<S>);
    58 |     replace?: boolean;
```

Seems like an internal bug

**Comment by dl748** [comment]
That type doesn't exist? I see H.LocationDescriptor in your code as well.  These looks like types from @types/history... history contains its own types.

Location is defined https://github.com/ReactTraining/history/blob/28c89f4091ae9e1b0001341ea60c629674e83627/packages/history/index.ts#L99

**Comment by gauravshah27** [comment]
I am seeing the same issue with LocationState  and I am not using @types/history package on my project. Is there a recommended migration path away from LocationState ?

**Comment by mjackson** [comment]
The type definitions in @types/history are for v4. v5 comes with its own type definitions, so you don't need @types/history anymore.

**Comment by jasonferrier** [comment]
FYI - for anyone still hitting this page in the search results, changing the import & type from `LocationState` to `Location` worked for me.

I'm using History v5.0.1.
