### ISSUE TITLE
5.0.0 breaks back button in preact-router

### ISSUE THREAD

**Issue by merlinpatt** [remix-run/history#856]
When attempting to upgrade to `history@5.0.0` in my preact app, the back button no longer works as it did previously. `history@4.10.1` works fine.

I found [this issue](https://github.com/preactjs/preact-router/issues/378) in `preact-router` but I think this may be a fix that `history` needs to do.

It may or may not be related to [this comment](https://github.com/ReactTraining/history/issues/811#issuecomment-664339506) on the [v5 undocumented breaking changes thread](https://github.com/ReactTraining/history/issues/811).

**Comment by StringEpsilon** [comment]
[This comment](https://github.com/preactjs/preact-router/issues/378#issuecomment-719484340) makes me pretty sure that the breakage came from the change in signature for the `history.listen()` callback. 

I documented that in [my gist here](https://gist.github.com/StringEpsilon/47820cc961c8d82f3b71dc856b5cc616#historylisten) and  midahp effectively came up with the same workaround.

**Comment by mjackson** [comment]
It sounds like this is an issue that preact-router needs to fix to be compatible with v5.
