### ISSUE TITLE
Why search is behind hash in HashRouter?

### ISSUE THREAD

**Issue by lanistor** [remix-run/history#858]
Hash positioned after search is standard, why `history` put search behind hash?

This caused lots of problems, such as:
1. window.location.search is empty.
2. Get request will not send search, so the server cannot react as expect.

**Comment by n00el** [comment]
Same problem

**Comment by StringEpsilon** [comment]
As per documentation (https://github.com/ReactTraining/history/blob/master/docs/api-reference.md#createhashhistory):

> The main difference between this and browser history is that a hash history stores the current location in the hash portion of the URL, which means that it is not ever sent to the server.

Putting the query (or search) in front of the hash would break applications that rely on fact that no request is made against the server.
