### ISSUE TITLE
Consider using `unknown` instead of `any` for `location.state`

### ISSUE THREAD

**Issue by OliverJAsh** [remix-run/history#903]
Since [v5.0.2], `location.state` now has type `any`. https://github.com/remix-run/history/commit/04a01ad4500720e26ebbf3d9cfefbd6c1a86be84

I appreciate why generics were not useful here, however I think it would be better to `unknown` instead of `any`.

`any` completely disables type checking, meaning we can make mistakes such as:

```ts
// no compile-time type error (❌) but throws at runtime
location.state.i.do.not.exist;
```

On the other hand, `unknown` will error in this case:

```ts
// compile-time type error ✅
location.state.i.do.not.exist;
```

We are forced to narrow and refine the `unknown` type using type guards:

```ts
interface ModalLocation extends Location {
  state: { foo: string }
}
 
const isObject = (candidate: unknown): candidate is object =>
    typeof candidate === 'object' && candidate !== null;

type DictionaryLike = { [index: string]: unknown; };
const isDictionaryLike = (
    candidate: unknown,
): candidate is DictionaryLike => isObject(candidate);

const isModalLocation = (location: Location): location is ModalLocation => {
  return isDictionaryLike(u) && typeof u.foo === 'string'
}

// compile-time type error ✅
location.state.foo;

if (isModalLocation(location)) {
  // no compile-time type error ✅
  location.state.foo;
}
```

The commit message mentions that one reason to use `any` is because that's how TypeScript defines `window.history.state`:

> the built-in types for `window.history.state` is `any`

However, I'm not sure this is a good precedent. Like many other built-in types, the definition of `window.history.state` was written before TypeScript had the `unknown` type. TypeScript is gradually moving towards `unknown`. For example, [the type of an error in a `catch` block used to be `any` but it is now `unknown` in strict mode](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables).

If a user doesn't care about validation and type safety, they can use a type assertion as an escape hatch.

```ts
// no compile-time type error ✅
(location.state as any).i.do.not.exist;
```

This way, type safety is the default, but the user can easily opt-out.

On the other hand, if we continue to use `any` as the type for `location.state` then users who do care about type safety might not realise that an `any` type is slipping into their code.

[v5.0.2]: https://github.com/remix-run/history/releases/tag/v5.0.2

**Comment by timdorr** [comment]
The bigger issue here is that breaking changes to the types were released in a patch version.

I'm working on reverting this. You can break types like this under semantic versioning.

**Comment by timdorr** [comment]
OK, 5.1.0 is out. Phew!

I would also vote this as a good idea, but it's probably going to need to be a major version. Any TS user is going to immediately get errors, unless they are already diligent about type guards for `state`. I don't think most are, which is understandable, so that would be disruptive despite being the right thing to do.

**Comment by pshrmn** [comment]
Breaking type changes in a package that provides its own types is an interesting problem. With `definitely-typed`, there is an expectation to pin your type packages to avoid breaking changes since they don't follow semver, but I don't know if following semver major semantics for type-only changes makes sense entirely here. Would react-router then need to support a range of major `history` versions so that users with the `object | null` assumption don't have to fix typing errors?

**Comment by samhh** [comment]
I think you can make the case that `any` is a massive footgun and therefore its removal is a bugfix, which is semver-compliant.

**Comment by sathiya-pyramidions** [comment]
#925 @timdorr please check this one.

**Comment by timdorr** [comment]
This is done in 5.2.0: https://github.com/remix-run/history/releases/tag/v5.2.0

**Comment by alecglen** [comment]
@OliverJAsh I was using the `any` definition and am now following your example to convert my code to be type safe. It makes sense up until `isModalLocation` where I am confused about the variable `u`. Is that meant to be `location.state`?

**Comment by OliverJAsh** [comment]
@alecglen Yes sorry—fixed my example.
