### ISSUE TITLE
Cannot read properties of undefined (reading 'pathname'). After upgrate to react router 6 

### ISSUE THREAD

**Issue by sergeu90** [remix-run/history#905]
Hello everyone. I don't know it is problem in the history library or connected-react-router or in react-router.
After upgrade react-router-dom 5.3.0 to 6.0.0 i have error 
Cannot read properties of undefined (reading 'pathname')
![image](https://user-images.githubusercontent.com/7217517/140474239-d55bdbf7-eec5-4fd5-90fb-de6706aff6b0.png)

Could you please help me. Who have same error after upgrade.

**Comment by sergeu90** [comment]
https://github.com/supasate/connected-react-router/issues/543

**Comment by dxmz** [comment]
please read it!
https://stackoverflow.com/questions/69859509/cannot-read-properties-of-undefined-reading-pathname-when-testing-pages-in/70604506
