### ISSUE TITLE
v5 createPath issue with null values. was fine in v4

### ISSUE THREAD

**Issue by salvoravida** [remix-run/history#907]
push({pathname:'login', hash:null})  => url created "loginnull"

the problem is with the history v5:
https://github.com/remix-run/history/blob/main/packages/history/index.ts#L1052

it was fine with history v4
https://github.com/remix-run/history/blob/v4/modules/PathUtils.js#L56

related issue: https://github.com/salvoravida/redux-first-history/issues/53

**Comment by brophdawg11** [comment]
This should have been fixed in [5.2.0](https://github.com/remix-run/history/releases/tag/v5.2.0) via #813.  Could you check again and re-open if it's still an issue after `5.2.0`?  Thanks!
